FoodWorld.Web/Pages/About.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FoodWorld.Pages
{
    public class AboutModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Your application description page.";
        }
    }
}

FoodWorld.Web/Pages/Contact.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FoodWorld.Pages
{
    public class ContactModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Your contact page.";
        }
    }
}

FoodWorld.Web/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace FoodWorld.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

FoodWorld.Web/Pages/Foods/List.cshtml.cs
using FoodWorld.Core;
using FoodWorld.Data;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Collections.Generic;

namespace FoodWorld.Web.Pages.Foods
{
    public class ListModel : PageModel
    {
        private readonly IFoodData foodData;

        public IEnumerable<Food> Foods { get; set; }

        public ListModel(IFoodData foodData)
        {
            this.foodData = foodData;
        }

        public void OnGet(int restaurantId)
        {
            Foods = this.foodData.GeFoodBytRestaurantID(restaurantId);
        }
    }
}

FoodWorld.Web/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FoodWorld.Pages
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

FoodWorld.Web/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FoodWorld.Pages
{
    public class PrivacyModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

FoodWorld.Web/Pages/Restaurants/ClientRestaurants.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace OdeToFood.Pages.Restaurants
{
    public class ClientRestaurantsModel : PageModel
    {

    }
}

FoodWorld.Web/Pages/Restaurants/Delete.cshtml.cs
using FoodWorld.Core;
using FoodWorld.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FoodWorld.Pages.Restaurants
{
    public class DeleteModel : PageModel
    {
        private readonly IRestaurantData restaurantData;

        public Restaurant Restaurant { get; set; }

        public DeleteModel(IRestaurantData restaurantData)
        {
            this.restaurantData = restaurantData;
        }

        public IActionResult OnGet(int restaurantId)
        {
            Restaurant = restaurantData.GetById(restaurantId);
            if (Restaurant == null)
            {
                return RedirectToPage("./NotFound");
            }
            return Page();
        }

        public IActionResult OnPost(int restaurantId)
        {
            var restaurant = restaurantData.Delete(restaurantId);
            restaurantData.Commit();

            if (restaurant == null)
            {
                return RedirectToPage("./NotFound");
            }

            TempData["Message"] = $"{restaurant.Name} deleted";
            return RedirectToPage("./List");
        }
    }
}

FoodWorld.Web/Pages/Restaurants/Detail.cshtml.cs
using FoodWorld.Core;
using FoodWorld.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FoodWorld.Pages.Restaurants
{
    public class DetailModel : PageModel
    {
        private readonly IRestaurantData restaurantData;

        [TempData]
        public string Message { get; set; }

        public Restaurant Restaurant { get; set; }

        public DetailModel(IRestaurantData restaurantData)
        {
            this.restaurantData = restaurantData;
        }

        public IActionResult OnGet(int restaurantId)
        {
            Restaurant = restaurantData.GetById(restaurantId);
            if (Restaurant == null)
            {
                return RedirectToPage("./NotFound");
            }
            return Page();
        }
    }
}

FoodWorld.Web/Pages/Restaurants/Edit.cshtml.cs
using FoodWorld.Core;
using FoodWorld.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;

namespace FoodWorld.Pages.Restaurants
{
    public class EditModel : PageModel
    {
        private readonly IRestaurantData restaurantData;
        private readonly IHtmlHelper htmlHelper;

        [BindProperty]
        public Restaurant Restaurant { get; set; }
        public IEnumerable<SelectListItem> Cuisines { get; set; }

        public EditModel(IRestaurantData restaurantData,
                         IHtmlHelper htmlHelper)
        {
            this.restaurantData = restaurantData;
            this.htmlHelper = htmlHelper;
        }

        public IActionResult OnGet(int? restaurantId)
        {
            Cuisines = htmlHelper.GetEnumSelectList<CuisineType>();
            if (restaurantId.HasValue)
            {
                Restaurant = restaurantData.GetById(restaurantId.Value);
            }
            else
            {
                Restaurant = new Restaurant();
            }
            if (Restaurant == null)
            {
                return RedirectToPage("./NotFound");
            }
            return Page();
        }

        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                Cuisines = htmlHelper.GetEnumSelectList<CuisineType>();
                return Page();
            }

            if (Restaurant.Id > 0)
            {
                restaurantData.Update(Restaurant);
            }
            else
            {
                restaurantData.Add(Restaurant);
            }
            restaurantData.Commit();
            TempData["Message"] = "Restaurant saved!";
            return RedirectToPage("./Detail", new { restaurantId = Restaurant.Id });
        }
    }
}

FoodWorld.Web/Pages/Restaurants/List.cshtml.cs
using FoodWorld.Core;
using FoodWorld.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using System.Collections.Generic;

namespace FoodWorld.Pages.Restaurants
{
    public class ListModel : PageModel
    {
        private readonly IConfiguration config;
        private readonly IRestaurantData restaurantData;
        private readonly ILogger<ListModel> logger;

        public string Message { get; set; }
        public IEnumerable<Restaurant> Restaurants { get; set; }

        [BindProperty(SupportsGet = true)]
        public string SearchTerm { get; set; }

        public ListModel(IConfiguration config,
                         IRestaurantData restaurantData,
                         ILogger<ListModel> logger)
        {
            this.config = config;
            this.restaurantData = restaurantData;
            this.logger = logger;
        }

        public void OnGet()
        {
            logger.LogError("Executing ListModel");
            Message = config["Message"];
            Restaurants = restaurantData.GetRestaurantsByName(SearchTerm);
        }
    }
}

FoodWorld.Web/ViewComponents/RestaurantCountViewComponent.cs
using FoodWorld.Data;
using Microsoft.AspNetCore.Mvc;

namespace OdeToFood.ViewComponents
{
    public class RestaurantCountViewComponent
         : ViewComponent
    {
        private readonly IRestaurantData restaurantData;

        public RestaurantCountViewComponent(IRestaurantData restaurantData)
        {
            this.restaurantData = restaurantData;
        }

        public IViewComponentResult Invoke()
        {
            var count = restaurantData.GetCountOfRestaurants();
            return View(count);
        }

    }
}

FoodWorld.Web/Pages/About.cshtml
@page
@model AboutModel
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@Model.Message</h3>

<p>Use this area to provide additional information.</p>
<div>
    Hi!
</div>

FoodWorld.Web/Pages/Contact.cshtml
@page
@model ContactModel
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@Model.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

FoodWorld.Web/Pages/Foods/List.cshtml
@page "{restaurantId:int?}"
@model FoodWorld.Web.Pages.Foods.ListModel
@{ ViewData["Title"] = "Food Menu"; }

<h1>Restaurant Menu</h1>

<div class="row">
    <div class="col">
        @foreach (var food in Model.Foods)
        {
            <div class="card">
                <div class="card-body">
                    <h3 class="card-title">@food.Name</h3>
                    <span>@food.Description</span><br />
                    <span>Price: $@food.Price</span>
                </div>
                <div class="card-footer">
                    <a class="btn btn-lg"
                       asp-page="../Restaurants/List">
                        <i class="fa fa-backward"></i>
                    </a>
                </div>

            </div>
        }
    </div>
</div>

FoodWorld.Web/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}


<h1>Food World</h1>
<p class="lead">Foodworld Private Limited operates a chain of good restaurants<br> All you get is good quality of food</p>

FoodWorld.Web/Pages/Restaurants/ClientRestaurants.cshtml
@page
@model OdeToFood.Pages.Restaurants.ClientRestaurantsModel
@{
    ViewData["Title"] = "ClientRestaurants";
}

<h2>Client Restaurants</h2>

<table class="table" id="restaurants">

</table>

@section Scripts {

        <script src="~/node_modules/datatables.net/js/jquery.dataTables.js"></script>
        <script src="~/node_modules/datatables.net-bs/js/dataTables.bootstrap.js"></script>
        <link href="~/node_modules/datatables.net-bs/css/dataTables.bootstrap.css" rel="stylesheet" />
    
        <script>

            $(function () {

                var cuisines = ["Unknown", "Mexican", "Italian", "Indian"]

                $.ajax("/api/restaurants/",
                    { method: "get" })
                    .then(function (response) {
                        $("#restaurants").dataTable({
                            data: response,
                            columns: [
                                { "data": "name" },
                                { "data": "location" },
                                {
                                    "data": "cuisine", "render": function (data) {                                      
                                        return cuisines[data];
                                    }
                                }
                            ]
                        });
                    });
            });


        </script>
}

FoodWorld.Web/Pages/Restaurants/Delete.cshtml
@page "{restaurantId}"
@model FoodWorld.Pages.Restaurants.DeleteModel
@{ ViewData["Title"] = "Delete"; }


<h2>Delete!</h2>
<div class="alert alert-danger">
    Are you sure you want to delete @Model.Restaurant.Name?
</div>
<form method="post">
    <button type="submit" class="btn btn-danger">Yes!</button>
    <a asp-page="List" class="btn btn-outline-primary">Cancel</a>
</form>

FoodWorld.Web/Pages/Restaurants/Detail.cshtml
@page "{restaurantId:int}"

@model FoodWorld.Pages.Restaurants.DetailModel
@{ ViewData["Title"] = "Detail"; }

<h2>@Model.Restaurant.Name</h2>
<div>
    Id: @Model.Restaurant.Id
</div>
<div>
    Location: @Model.Restaurant.Location
</div>
<div>
    Cuisine: @Model.Restaurant.Cuisine
</div>

@if (Model.Message != null)
{
<div class="alert alert-info">@Model.Message</div>}

<a asp-page="./List" class="btn btn-outline-primary">All Restaurants</a>

FoodWorld.Web/Pages/Restaurants/Edit.cshtml
@page "{restaurantId:int?}"
@model FoodWorld.Pages.Restaurants.EditModel
@{ ViewData["Title"] = "Edit"; }

<h2>Editing @Model.Restaurant.Name</h2>

<form method="post">

    <input type="hidden" asp-for="Restaurant.Id" />
    <div class="form-group">
        <label asp-for="Restaurant.Name"></label>
        <input asp-for="Restaurant.Name" class="form-control" />
        <span class="text-danger" asp-validation-for="Restaurant.Name"></span>
    </div>
    <div class="form-group">
        <label asp-for="Restaurant.Location"></label>
        <input asp-for="Restaurant.Location" class="form-control" />
        <span class="text-danger" asp-validation-for="Restaurant.Location"></span>
    </div>
    <div class="form-group">
        <label asp-for="Restaurant.Cuisine"></label>
        <select class="form-control" asp-for="Restaurant.Cuisine"
                asp-items="Model.Cuisines"></select>
        <span class="text-danger" asp-validation-for="Restaurant.Cuisine"></span>
    </div>

    <button type="submit" class="btn btn-primary">Save</button>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

FoodWorld.Web/Pages/Restaurants/List.cshtml
@page
@model FoodWorld.Pages.Restaurants.ListModel
@{ ViewData["Title"] = "Restaurants"; }

<h1>Restaurants</h1>

<form method="get">
    <div class="form-group">
        <div class="input-group">
            <input type="search" class="form-control"
                   asp-for="SearchTerm" />
            <span>
                <button class="btn btn-default">
                    <i class="fas fa-search"></i>
                </button>
            </span>
        </div>
    </div>
</form>

<div class="row">
    <div class="col">
        @foreach (var restaurant in Model.Restaurants)
        {
<partial name="_Summary" model="restaurant" />}

        <a asp-page="./Edit" class="btn btn-primary btn-lg btn-block">Add New</a>
    </div>
</div>


@section footer {
    <div>@Model.Message</div>
}

FoodWorld.Web/Pages/Restaurants/NotFound.cshtml
@page
@{
    ViewData["Title"] = "NotFound";
}

<h2>Your restaurant was not found</h2>
<a asp-page="./List" class="btn btn-primary">See All Restaurants</a>

FoodWorld.Web/Pages/Restaurants/_Summary.cshtml
@using FoodWorld.Core
@model Restaurant

<div class="card">
    <div class="card-body">
        <h3 class="card-title">@Model.Name</h3>
        <span>Location: @Model.Location</span>
        <span>Cuisine: @Model.Cuisine</span>
    </div>
    <div class="card-footer">
        <a class="btn btn-lg"
           asp-page="./Detail"
           asp-route-restaurantId="@Model.Id">
            <i class="fa fa-search-plus"></i>
        </a>
        <a class="btn btn-lg"
           asp-page="./Edit"
           asp-route-restaurantId="@Model.Id">
            <i class="fa fa-edit"></i>
        </a>
        <a class="btn btn-lg"
           asp-page="./Delete"
           asp-route-restaurantId="@Model.Id">
            <i class="fa fa-trash"></i>
        </a>
        <a class="btn btn-lg"
           asp-page="../Foods/List"
           asp-route-restaurantId="@Model.Id">
            <i class="fa fa-utensils"></i>
        </a>
    </div>

</div>

FoodWorld.Web/Pages/Shared/Components/RestaurantCount/Default.cshtml
@model int

<div>
    There are @Model restaurants here. <a asp-page="/Restaurants/List">See them all!</a>
</div>

FoodWorld.Web/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FoodWorld</title>

    <environment include="Development">
        <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
        <link href="~/node_modules/@@fortawesome/fontawesome-free/css/all.css" rel="stylesheet" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="//ajax.aspnetcdn.com/ajax/bootstrap/4.6.0/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet"
              href="//cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css"
              asp-fallback-href="~/lib/@@fortawesome/fontawesome-free/css/all.css"
              asp-fallback-test-class="fa"
              asp-fallback-test-property="font-family"
              asp-fallback-test-value="FontAwesome" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>

</head>
<body>

    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">FoodWorld</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Restaurants/List">Restaurants</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/About">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Contact">Contact</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            <environment include="Development">
                <system-info></system-info>
            </environment>

            @RenderSection("footer", required: false)
            <vc:restaurant-count></vc:restaurant-count>
            &copy; 2021 - FoodWorld  - <a asp-area="" asp-page="/Privacy">Privacy</a>
            <img src="/foodworld.png" />
        </div>
    </footer>

    <environment include="Development">
        <script src="~/node_modules/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.4.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.js"
                asp-fallback-test="window.jQuery"></script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/4.6.0/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>